# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Depoly Portfolio Application to AWS S3 Bucket (Static Web)

on:
  # TODO: reassign 'pull_request' to 'push' if code is not problem
  pull_request:
    # NOTE: `main` branch has rule of managing deploy portfolio app in my repo!
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: Build and Export App
        run: yarn export
