# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check All (ESLint and Stylelint)

on:
  pull_request:
    # NOTE: `main` branch has rule of managing deploy portfolio app in my repo!
    branches: ['main', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # NOTE: I use node.js v16.15(LTS).
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn

      - name: Check ESLint, Stylelint
        run: yarn lint:all
